### ISSUE TITLE
[質問] calc_neighbor.pyの72行目あたりについて

### ISSUE THREAD

**Issue by yaneura-no-gomi** [nkmr-lab/comic-speaker-recognitions#1]
先日メールでいろいろと質問させていただいたものです
コードの公開ありがとうございます
非常に助かっております

早速ですが、calc_neighbor.pyの72行目あたりについて質問があります
https://github.com/nkmr-lab/comic-speaker-recognitions/blob/74777c77759f60c0a75a54a24977819bb6ae5b8b/calc_neighbor.py#L72
72行目までで、テキストとキャラクターの距離計算を行っていると思うのですが、そこから、
コメントとして記載されている「得点が最大の方にすることにした」のところと
```
per_both['face'] = per_both['face'] * 1.5
```
の意図が気になって質問させていただきました
faceとbodyの距離を均一には扱っていないということでしょうか
また、1テキストごとにscores_dfにappendしていくper_normは出現キャラクターごとのテキストとの最短距離のSeriesという認識であっていますでしょうか

お忙しいところお手数ですが、回答していただければと思います
よろしくお願いいたします

**Comment by abekzk** [comment]
@yaneura-no-gomi 

自分でも酷い名前だと思うんですが、実際に研究で計算に使用したのがcalc_neighbor_nonface.pyの方になります。

こちらcalc_neighbor.pyと何が違うかと言うと、ご指摘の一行をコメントアウトしてるだけで他は何も変わりません笑（diffを取ってみるとわかると思います）

https://github.com/nkmr-lab/comic-speaker-recognitions/blob/74777c77759f60c0a75a54a24977819bb6ae5b8b/calc_neighbor_nonface.py#L73


当初は顔が近いほうが有利になるように、顔の得点のみ1.5倍にするように設定していました。しかし結果的には、顔との距離に重みを置かない方が精度が良かったため、その計算の箇所だけを抜いたcalc_neighbor_nonface.py を作ってます。

おそらく、顔に重みを付けた場合と計算結果を比較が必要になったときに、1.5倍のコードも残しておこうと当時の自分は思ったのですね。。。

**Comment by abekzk** [comment]
また、per_normは（これまた変数名としてはわかりにくさMAXですが）距離ではなく距離をもとにしたスコア（発話者っぽさを数値にしたもの。実際の推定で使います）が入っています。このスコアの計算には、いくつか段階があり、順番に説明しますと、

まずは以下の箇所で顔・体との距離を求めます
https://github.com/nkmr-lab/comic-speaker-recognitions/blob/74777c77759f60c0a75a54a24977819bb6ae5b8b/calc_neighbor_nonface.py#L62-L63

次に、最長距離（画像の対角線）をもとに距離を正規化し、その値を1から引いた値をスコアにします。こうすることで、距離が短いほどスコアが高くなります。
https://github.com/nkmr-lab/comic-speaker-recognitions/blob/74777c77759f60c0a75a54a24977819bb6ae5b8b/calc_neighbor_nonface.py#L65-L66

faceとbodyを比較して、その値が高い方のスコアを利用します
https://github.com/nkmr-lab/comic-speaker-recognitions/blob/74777c77759f60c0a75a54a24977819bb6ae5b8b/calc_neighbor_nonface.py#L74


この時点で変数`per`は、indexにキャラクタのID、valueにスコアが入ってます。その上で、1つのセリフに対する発話者のスコアの合計値を1に正規化するため、さらにスコアの合計で割ることにしてます
https://github.com/nkmr-lab/comic-speaker-recognitions/blob/74777c77759f60c0a75a54a24977819bb6ae5b8b/calc_neighbor_nonface.py#L76-L77

これでやっと「1つのセリフに対する正規化されたスコア」を手に入れることができます。データの型はご指摘の通りSeries型で、それをDataFrameに入れ、最終的にはcsvで出力するという処理になります。

長い説明になりましたが、スコアの考え方が少し特殊で難しいかと思います。
基本的には、いろんな計算で正規化されたスコアを計算する→それらを足し合わせ、最終的に最もスコアが高かったキャラクタを発話者として選ぶという手法を取っています！

**Comment by abekzk** [comment]
どうでしょう、回答になってますでしょうか？笑

**Comment by yaneura-no-gomi** [comment]
回答ありがとうございます。
非常に分かりやすかったです！
