### ISSUE TITLE
[質問] 動作手順について

### ISSUE THREAD

**Issue by yaneura-no-gomi** [nkmr-lab/comic-speaker-recognitions#2]
度々申し訳ありません
論文中の表6.2および6.3にある実験結果を再現するには、リポジトリ内のどのコードをどの順番で動かせば良いのか教えていただきたいです

何度も申し訳ないのですが、何卒宜しくお願い致します

**Comment by abekzk** [comment]
@yaneura-no-gomi 

- formatting.py（データの整形）
- calc_XXX.py（手法ごとにスコア書き出し）
- predict.py（スコアを合算して発話者を推定）
- evaluate.py（推定結果から正解率を計算）

が実行の手順になります。

ただし、`data`というディレクトリを作ってその中に整形済みのデータセットを配置する必要があることや、manga109のpythonライブラリを独自に改造してるなど、現状ではこのコードをそのまま他者が動かすのは困難になってます（申し訳ない🙇‍♂️）

研究のための実装などが急ぎでしたら、上記のコードを追っていただくほかないですが、他者が使えないのは中村研究室でも問題になるので、これからアップデートする予定となります。

各コードに関して他に質問などございましたら、随時ご連絡ください。こちらのアップデートが完了の際にも、またご連絡いたします。

**Comment by yaneura-no-gomi** [comment]
回答ありがとうございます。
急かすつもりは全くないので、中村研究室様の予定で進めていただいて全然大丈夫です！
アップデート完了を楽しみにしております！

**Comment by abekzk** [comment]
@yaneura-no-gomi 
お待たせしました、本コードによる実験を手軽に実行できるようにアップデートいたしました！:tada:

基本的にはREADMEに記載している手順を実行することで、論文と同じ結果が得られると思います。
不明な点などありましたら、またissueで質問してください。
macでは動作を確認したのですが、windowsでは未確認のためもし動かないなどの問題があればご報告ください。

また、推定のために使用した整形済みのデータも公開することにいたしました。
同じくREADMEにダウンロードのためのリンクが貼られているのでご確認ください:thumbsup:

【備考】
- Mecabのインストールや設定に関しては一人称・語尾による推定を使用しない場合は必要ありません
- 実行方法にキーワードによって手法を指定する場面がありますが、論文における4つの手法と対応するキーワードを載せておきます
  - neighbor_nonface: セリフとキャラクタの距離による計算
  - inframe: 同じコマ内にいるキャラクタの情報による計算
  - taildirection3: 吹き出しのしっぽ方向による計算
  - firstperson,endingword:  一人称+語尾による計算

**Comment by yaneura-no-gomi** [comment]
ありがとうございます！
早速使わせていただきます！
