### ISSUE TITLE
中心座標を求める際の引数ミス

### ISSUE THREAD

**Issue by yaneura-no-gomi** [nkmr-lab/comic-speaker-recognitions#5]
https://github.com/nkmr-lab/comic-speaker-recognitions/blob/86d36a62fe5bb75c3cd5c9e851e975728a9b5b64/calc_neighbor_nonface.py#L40

calc_box_centerの引数で、ymaxではなくxmaxが渡されていました
これを直した所、距離のみで74.3%まで精度が上がりました
一応報告させていただきました

**Comment by abekzk** [comment]
なんと！！これはかなりクリティカルなバグですね...orz
共有ありがとうございます！
計算結果についても今後の参考にさせていただきます🙇‍♂️

**Comment by abekzk** [comment]
@yaneura-no-gomi 

こちら(#6 )で対応中となりますが、bodyだけでなくfaceの計算でも同様にミスがありました。
両方を修正したところ、精度は78.5%となります。
修士論文の精度との差は8%ほどですが、セリフの件数としては約9,700件もの正解が増えたこととなります！
（もしどちらも修正した上で74.3％でしたら再度指摘していただけると助かります。。。）

ご指摘いただき大変助かりました！
マージ後にこちらのissueはクローズさせていただきます。
